### ISSUE TITLE
Database Questions

### ISSUE THREAD

**Issue by smithsa** [ryantimjohn/action_network_1on1_tracker#1]
@ryantimjohn so far I know we have 'Users' and '1-on-1' as entities. Is there anything else you can think of we would want to store in a database? I will post basic database schema in basecamp and then you can add to it or add comments

**Comment by ryantimjohn** [comment]
Commented and updated in basecamp. One of the main requests I got from people vis-a-vis the app was that it be quick to add info, otherwise they felt like organizers wouldn't use it. So, I removed phone, etc. I also added the form and person endpoints to the schema so that we could access them for PUT requests.
